# Generated by Django 5.2.3 on 2025-06-27 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Wedding', 'Wedding'), ('Birthday', 'Birthday'), ('Graduation', 'Graduation'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
    ]
